### PR TITLE
feat: Add a new gitlab runner construct with AutoScalingGroup

### PR DESCRIPTION
**Pull request by gotodeploy**
Now autoscaling group is controlling the number of EC2 instances with a simpler unregistering lambda function.

### CODE REVIEW

**Comment by guan840912** [comment]
hi ~~ @gotodeploy ,  did you run yarn build to update API.md on your local laptop ?

**Comment by gotodeploy** [comment]
@guan840912 I appreciate you to point out why the build failed.

**Comment by guan840912** [comment]
hi @gotodeploy, I have some ideas, can we discuss them on [twitter](https://twitter.com/neil_kuan) or mail guan840912@gmail.com ?

**Comment by gotodeploy** [comment]
@guan840912 Sent PM on slack(cdk-dev).

**Comment by guan840912** [comment]
LGTM !!!!! 
Very thank you , @gotodeploy  😊😊😊

**Review by guan840912 — APPROVED** [review]

**Pull request merged**
